# seed_games.py
from dotenv import load_dotenv
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine, select
from models import Game
from db import Base
import os

load_dotenv()
engine = create_engine(os.getenv("DATABASE_URL"))
Session = sessionmaker(bind=engine, autoflush=False)

juegos = [
  {"nombre":"EA FC26","foto":"/public/fc26.jpg","link":"https://www.ea.com/es-es/games/fifa/fc-26","descripcion":"EA Sports FC 26 es el nuevo nombre del popular videojuego de fútbol desarrollado por EA Sports, que anteriormente se conocía como FIFA. El mejor juego de futbol del mercado. Si tu vida es el fútbol, este es tu juego! ","popularidad":5,"trailer":"https://www.youtube.com/watch?v=KdKYsbm9WAU","categoria":"Deportes"},
  {"nombre":"NBA 2K26","foto":"/public/2k26.jpg","link":"https://nba.2k.com/es-ES/2k26/","descripcion":"NBA 2K26 es la última entrega de la popular serie de videojuegos de baloncesto desarrollada por Visual Concepts y publicada por 2K Sports. Con gráficos impresionantes, jugabilidad realista y una amplia variedad de modos de juego, NBA 2K26 ofrece a los jugadores la oportunidad de experimentar la emoción del baloncesto profesional.","popularidad":4,"trailer":"https://www.youtube.com/watch?v=Mh57YWNaQC4","categoria":"Deportes"},
  {"nombre":"Clash Royale","foto":"/public/clash.jpg","link":"https://clashroyale.com/es/","descripcion":"Clash Royale es un juego de estrategia en tiempo real desarrollado por Supercell, los creadores de Clash of Clans. En este juego, los jugadores coleccionan y mejoran cartas que representan tropas, hechizos y defensas, y las utilizan para atacar las torres del oponente mientras defienden las suyas propias. El objetivo es destruir la torre del rey del oponente para ganar coronas y avanzar en la clasificación.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=0Cj86Q_I7zU","categoria":"Estrategia"},
  {"nombre":"Call of Duty Black Ops VI","foto":"/public/cod.jpg","link":"https://www.callofduty.com/es/","descripcion":"Call of Duty: Black Ops 6 es la última entrega de la popular serie de videojuegos de disparos en primera persona desarrollada por Infinity Ward y publicada por Activision. El juego continúa la historia de los eventos globales y presenta una campaña intensa, así como modos multijugador competitivos y cooperativos.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=K7wW6V0OiIU","categoria":"Acción"},
  {"nombre":"Fortnite","foto":"/public/fortnite.jpg","link":"https://www.epicgames.com/fortnite/es-ES/home","descripcion":"Fortnite es un videojuego en línea desarrollado por Epic Games que combina elementos de disparos en tercera persona, construcción y supervivencia. El juego se lanzó en 2017 y rápidamente se convirtió en un fenómeno cultural, atrayendo a millones de jugadores en todo el mundo. Fortnite ofrece varios modos de juego, siendo el más popular el modo Battle Royale, donde 100 jugadores compiten entre sí para ser el último en pie en una isla llena de armas, recursos y desafíos.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=WJW-bzXZM8M","categoria":"Acción"},
  {"nombre":"Minecraft","foto":"/public/minecraft.jpg","link":"https://www.minecraft.net/es-es","descripcion":"Minecraft es un videojuego de construcción y aventura desarrollado por Mojang Studios. Lanzado en 2011, Minecraft permite a los jugadores explorar un mundo generado proceduralmente compuesto por bloques tridimensionales. Los jugadores pueden recolectar recursos, construir estructuras, crear herramientas y enfrentarse a criaturas en un entorno abierto y creativo. El juego ofrece varios modos de juego, incluyendo el modo supervivencia, donde los jugadores deben gestionar su salud y hambre, y el modo creativo, que permite a los jugadores construir libremente sin restricciones.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=MmB9b5njVbA","categoria":"Aventura"},
  {"nombre":"F1 2025","foto":"/public/f1.jpg","link":"https://www.ea.com/es/games/f1/f1-25","descripcion": "F1 2025 es la última entrega de la serie de videojuegos de Fórmula 1 desarrollada por Codemasters y publicada por Electronic Arts. El juego ofrece una experiencia de simulación realista de la temporada 2025 de Fórmula 1, con todos los equipos, pilotos y circuitos oficiales. Los jugadores pueden competir en carreras individuales, campeonatos completos o participar en modos multijugador en línea. F1 2025 presenta gráficos impresionantes, física realista y una jugabilidad mejorada, brindando a los fanáticos de la Fórmula 1 la oportunidad de vivir la emoción del deporte desde la comodidad de su hogar.","popularidad":4,"trailer":"https://www.youtube.com/watch?v=gBS3xgF93qo","categoria":"Deportes"},
  {"nombre":"MotoGP 2025","foto":"/public/motogp.jpg","link":"https://milestone.it/es/games/motogp-25/","descripcion":"MotoGP 2025 es la última entrega de la serie de videojuegos de motociclismo desarrollada por Milestone. El juego ofrece una experiencia de simulación realista de la temporada 2025 de MotoGP, con todos los equipos, pilotos y circuitos oficiales. Los jugadores pueden competir en carreras individuales, campeonatos completos o participar en modos multijugador en línea. MotoGP 2025 presenta gráficos impresionantes, física realista y una jugabilidad mejorada, brindando a los fanáticos del motociclismo la oportunidad de vivir la emoción del deporte desde la comodidad de su hogar.","popularidad":4,"trailer":"https://www.youtube.com/watch?v=EQPXbsnBhEY","categoria":"Deportes"},
  {"nombre":"GTA V","foto":"/public/gta.jpg","link":"https://www.rockstargames.com/es/games/gta-v","descripcion":"Grand Theft Auto V (GTA V) es un videojuego de acción y aventura desarrollado por Rockstar North y publicado por Rockstar Games. Lanzado en 2013, GTA V se ambienta en la ciudad ficticia de Los Santos, inspirada en Los Ángeles, y sigue las historias entrelazadas de tres protagonistas: Michael De Santa, Franklin Clinton y Trevor Philips. El juego ofrece un mundo abierto expansivo donde los jugadores pueden explorar libremente, participar en misiones, actividades secundarias y eventos aleatorios. GTA V es conocido por su narrativa envolvente, jugabilidad variada y gráficos impresionantes, convirtiéndolo en uno de los videojuegos más exitosos y aclamados de todos los tiempos.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=QkkoHAzjnUs","categoria":"Acción"},
  {"nombre":"Plants vs Zombies","foto":"/public/plants_vs_zombies.jpg","link":"https://www.ea.com/es-es/games/plants-vs-zombies","descripcion":"Plants vs. Zombies es un videojuego de estrategia y defensa de torres desarrollado por PopCap Games. Lanzado en 2009, el juego se centra en la defensa del jardín del jugador contra oleadas de zombis utilizando una variedad de plantas con habilidades únicas. Los jugadores deben colocar estratégicamente las plantas para detener el avance de los zombis y proteger su hogar. Plants vs. Zombies es conocido por su jugabilidad adictiva, gráficos coloridos y humor característico, convirtiéndolo en un título popular entre jugadores de todas las edades.","popularidad":3,"trailer":"https://www.youtube.com/watch?v=2jULUsBIUd0","categoria":"Estrategia"},
  {"nombre":"FAR CRY 6","foto":"/public/farcry.jpg","link":"https://www.ubisoft.com/es-es/game/far-cry/far-cry-6","descripcion": "Far Cry 6 es un videojuego de disparos en primera persona desarrollado por Ubisoft. Lanzado en 2021, el juego se ambienta en la isla ficticia de Yara, inspirada en Cuba, y sigue la historia de Dani Rojas, un guerrillero que lucha contra el régimen opresivo del dictador Antón Castillo, interpretado por Giancarlo Esposito. Far Cry 6 ofrece un mundo abierto expansivo donde los jugadores pueden explorar libremente, participar en misiones principales y secundarias, y utilizar una variedad de armas y vehículos para enfrentarse a las fuerzas del régimen. El juego es conocido por su narrativa envolvente, gráficos impresionantes y jugabilidad variada, brindando a los jugadores una experiencia emocionante y desafiante.","popularidad":3,"trailer":"https://www.youtube.com/watch?v=tSDMwngdkF4","categoria":"Acción"},
  {"nombre":"eFOOTBALL 2026","foto":"/public/efootball.jpg","link":"https://www.konami.com/efootball/es/","descripcion":"eFootball 2026 es la última entrega de la serie de videojuegos de fútbol desarrollada por Konami. Anteriormente conocido como Pro Evolution Soccer (PES), eFootball 2026 ofrece una experiencia de simulación realista del fútbol, con todos los equipos, ligas y jugadores oficiales. Los jugadores pueden competir en partidos individuales, torneos completos o participar en modos multijugador en línea. eFootball 2026 presenta gráficos impresionantes, física realista y una jugabilidad mejorada, brindando a los fanáticos del fútbol la oportunidad de vivir la emoción del deporte desde la comodidad de su hogar.","popularidad":3,"trailer":"https://www.youtube.com/watch?v=7LH1IvXl6_8","categoria":"Deportes"},
  {"nombre":"Tom Clancys Rainbow Six: Siege","foto":"/public/rainbow.jpg","link":"https://www.ubisoft.com/es-es/game/rainbow-six/siege","descripcion":"Tom Clancy's Rainbow Six Siege es un videojuego de disparos en primera persona desarrollado por Ubisoft. Lanzado en 2015, el juego se centra en el combate táctico entre equipos de operadores antiterroristas y terroristas. Los jugadores pueden elegir entre una variedad de operadores, cada uno con habilidades y equipamiento únicos, para completar objetivos como desactivar bombas, rescatar rehenes o asegurar áreas. Rainbow Six Siege es conocido por su jugabilidad estratégica, destructibilidad del entorno y enfoque en el trabajo en equipo, lo que lo convierte en un título popular en la escena de los deportes electrónicos.","popularidad":3,"trailer":"https://www.youtube.com/watch?v=BI9fgQY0d5I","categoria":"Acción"},
  {"nombre":"Score! Hero 2","foto":"/public/score_hero.jpg","link":"https://score-hero.softonic.com/android","descripcion":"Score! Hero 2 es un videojuego de fútbol desarrollado por First Touch Games. Lanzado en 2018, el juego permite a los jugadores crear y controlar a su propio héroe del fútbol, guiándolo a través de una carrera llena de desafíos y momentos emocionantes. A diferencia de los juegos de fútbol tradicionales, Score! Hero 2 se centra en la jugabilidad basada en niveles, donde los jugadores deben completar una serie de escenarios y objetivos específicos para avanzar en la historia. El juego presenta gráficos atractivos, controles intuitivos y una variedad de movimientos y habilidades para que los jugadores puedan realizar jugadas impresionantes y marcar goles espectaculares.","popularidad":2,"trailer":"https://www.youtube.com/watch?v=Wf3Q8OnayAg","categoria":"Deportes"},
  {"nombre":"Subway Surfers","foto":"/public/subway-surfers.jpg","link":"https://subwaysurfersonline.io/","descripcion":"Subway Surfers es un videojuego de carrera infinita desarrollado por Kiloo y SYBO Games. Lanzado en 2012, el juego sigue las aventuras de un joven grafitero llamado Jake, quien debe escapar de un inspector y su perro mientras corre por las vías del tren. Los jugadores deben esquivar obstáculos, recoger monedas y power-ups, y realizar acrobacias para avanzar en el juego. Subway Surfers es conocido por sus gráficos coloridos, jugabilidad adictiva y actualizaciones regulares que introducen nuevos personajes, tablas de surf y ubicaciones temáticas.","popularidad":4,"trailer":"https://www.youtube.com/watch?v=fGy-x3H-nxU","categoria":"Aventura"},
  {"nombre":"Gang Beasts","foto":"/public/gang_beasts.jpg","link":"https://gangbeasts.game/","descripcion":"Gang Beasts es un videojuego de lucha multijugador desarrollado por Boneloaf. Lanzado en 2017, el juego presenta personajes gelatinosos y coloridos que luchan en una variedad de entornos absurdos y peligrosos. Los jugadores pueden elegir entre varios modos de juego, incluyendo batallas libres, partidas personalizadas y modos cooperativos. Gang Beasts es conocido por su jugabilidad caótica y divertida, que combina elementos de lucha y plataformas, así como por su estilo visual único y humorístico.","popularidad":2,"trailer":"https://www.youtube.com/watch?v=Vz0BriND6pE","categoria":"Acción"},
  {"nombre":"Parchis STAR","foto":"/public/parchis.jpg","link":"https://parchisi-star-online.softonic.com/android","descripcion":"Parchis STAR es un videojuego de mesa basado en el clásico juego de Parchís, desarrollado por Gameberry Labs. Lanzado en 2018, el juego permite a los jugadores competir contra amigos o jugadores de todo el mundo en partidas en línea. Parchis STAR presenta gráficos coloridos y una interfaz fácil de usar, así como varias opciones de personalización para los tableros y fichas. El juego también incluye características sociales, como chat en vivo y la posibilidad de formar equipos, lo que lo convierte en una experiencia divertida y social para los amantes del Parchís.","popularidad":4,"trailer":"https://www.youtube.com/watch?v=Vm4A0OFVoIY","categoria":"Estrategia"},
  {"nombre":"Fall Guys","foto":"/public/fall.jpg","link":"https://www.fallguys.com/es-ES","descripcion":"Fall Guys: Ultimate Knockout es un videojuego de plataformas multijugador desarrollado por Mediatonic. Lanzado en 2020, el juego presenta a jugadores compitiendo en una serie de desafíos y minijuegos caóticos y coloridos, con el objetivo de ser el último jugador en pie. Fall Guys combina elementos de juegos de fiesta y battle royale, ofreciendo una experiencia divertida y accesible para jugadores de todas las edades. El juego es conocido por su estilo visual vibrante, personajes adorables y jugabilidad adictiva.","popularidad":4,"trailer":"https://www.youtube.com/watch?v=AyADwdiW7rQ","categoria":"Aventura"},
  {"nombre":"Among Us","foto":"/public/among_us.jpeg","link":"https://www.innersloth.com/gameAmongUs.php","descripcion": "Among Us es un videojuego multijugador en línea desarrollado por InnerSloth. Lanzado en 2018, el juego se ambienta en una nave espacial donde los jugadores asumen el papel de tripulantes que deben completar tareas mientras intentan descubrir quiénes entre ellos son impostores que buscan sabotear la misión y eliminar a los demás jugadores. Among Us es conocido por su jugabilidad social y cooperativa, que fomenta la comunicación y la estrategia entre los jugadores. El juego ganó una gran popularidad en 2020, convirtiéndose en un fenómeno cultural y siendo ampliamente jugado en plataformas como Twitch y YouTube.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=0YKjFoGxbec","categoria":"Estrategia"},
  {"nombre":"Clash of Clans","foto":"/public/clash_of_clans.jpg","link":"https://clashofclans.com/es/","descripcion":"Clash of Clans es un videojuego de estrategia en línea desarrollado por Supercell. Lanzado en 2012, el juego permite a los jugadores construir y gestionar su propia aldea, entrenar tropas y atacar las aldeas de otros jugadores para obtener recursos y trofeos. Los jugadores pueden unirse a clanes para colaborar en guerras de clanes y compartir estrategias. Clash of Clans es conocido por su jugabilidad adictiva, gráficos coloridos y actualizaciones regulares que introducen nuevos contenidos y características.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=XH3Xu1-cvII","categoria":"Estrategia"},
  {"nombre":"Call of Duty Black Ops III","foto":"/public/cod_bo3.jpg","link":"https://www.callofduty.com/es/blackops3","descripcion":"Call of Duty: Black Ops III es un videojuego de disparos en primera persona desarrollado por Treyarch y publicado por Activision. Lanzado en 2015, el juego se ambienta en un futuro distópico donde la tecnología avanzada y la guerra cibernética son predominantes. Black Ops III ofrece una campaña intensa, así como modos multijugador competitivos y cooperativos, incluyendo el popular modo Zombies. El juego es conocido por su jugabilidad rápida, gráficos impresionantes y una amplia variedad de armas y personalizaciones.","popularidad":4,"trailer":"https://www.youtube.com/watch?v=qAUYNIDEJ6o","categoria":"Acción"},
  {"nombre":"Brawl Stars","foto":"/public/brawl_stars.jpg","link":"https://brawlstars.com/es/","descripcion":"Brawl Stars es un videojuego de acción multijugador desarrollado por Supercell. Lanzado en 2018, el juego presenta partidas rápidas y frenéticas en las que los jugadores pueden elegir entre una variedad de personajes, conocidos como Brawlers, cada uno con habilidades y estilos de juego únicos. Brawl Stars ofrece varios modos de juego, incluyendo combates en equipo, capturar la bandera y supervivencia, lo que brinda a los jugadores una experiencia diversa y emocionante. El juego es conocido por sus gráficos coloridos, jugabilidad adictiva y actualizaciones regulares que introducen nuevos Brawlers, mapas y eventos.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=CaryjOdYFa0","categoria":"Acción"},
  {"nombre":"Candy Crush Saga","foto":"/public/candy_crush.jpg","link":"https://candycrushsaga.com/es/","descripcion":"Candy Crush Saga es un videojuego de rompecabezas desarrollado por King. Lanzado en 2012, el juego se basa en la mecánica de combinar tres o más caramelos del mismo color para eliminarlos del tablero y completar objetivos específicos en cada nivel. Candy Crush Saga presenta cientos de niveles desafiantes, cada uno con diferentes obstáculos y objetivos, lo que mantiene a los jugadores enganchados mientras avanzan a través del juego. El juego es conocido por sus gráficos coloridos, música pegajosa y jugabilidad adictiva, convirtiéndolo en uno de los juegos móviles más populares de todos los tiempos.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=gJjCGmMkAIw","categoria":"Estrategia"},
  {"nombre":"Clash of Kings","foto":"/public/clash_of_kings.jpg","link":"https://www.clashofkings.com/","descripcion":"Clash of Kings es un videojuego de estrategia en línea desarrollado por Elex Wireless. Lanzado en 2014, el juego permite a los jugadores construir y gestionar su propio reino, formar alianzas con otros jugadores y participar en guerras masivas por el control de territorios. Los jugadores pueden entrenar tropas, investigar tecnologías y mejorar sus edificios para fortalecer su ejército y defenderse de ataques enemigos. Clash of Kings es conocido por su jugabilidad estratégica, gráficos detallados y eventos en tiempo real que mantienen a los jugadores comprometidos.","popularidad":2,"trailer":"https://www.youtube.com/watch?v=jIzKNhh1tHM","categoria":"Estrategia"},
  {"nombre":"TicTacToe","foto":"/public/TicTacToe.jpg","link":None,"descripcion":'Tres en Raya es un clásico juego de estrategia y lógica para dos jugadores, también conocido como “Tic Tac Toe”. El objetivo es alinear tres símbolos iguales —ya sea X o O— en una cuadrícula de 3x3, ya sea en línea horizontal, vertical o diagonal. Aunque sencillo en apariencia, el juego requiere planificación y pensamiento anticipado para bloquear los movimientos del oponente y crear oportunidades de victoria. Su simplicidad lo convierte en una experiencia accesible y divertida para jugadores de todas las edades.',"popularidad":2,"trailer":None,"categoria":"Estrategia"},
  {"nombre":"Mario Kart 8 Deluxe","foto":"/public/mario_kart.jpg","link":"https://www.nintendo.com/es-es/Juegos/Juegos-de-Nintendo-Switch/Mario-Kart-8-Deluxe-1173281.html?srsltid=AfmBOoolVFlN4beu1igOeXTY36J6UbS4zqjW7IRZlG8JEOVBDT2oDD7a","descripcion":"Mario Kart 8 Deluxe es el juego de carreras arcade de Nintendo por excelencia. Compite en circuitos llenos de atajos y peligros, usa objetos icónicos para adelantar rivales y disfruta de modos para 1–4 jugadores en local u online. Incluye todo el contenido de MK8 y mejoras en jugabilidad y batalla.","popularidad":5,"trailer":"https://www.youtube.com/watch?v=tKlRN2YpxRE","categoria":"Deportes"},
  {"nombre":"Red Dead Redemption II","foto":"/public/red_dead_redemption_II.jpg","link":"https://www.rockstargames.com/reddeadredemption2","descripcion":"Red Dead Redemption II es una aventura de mundo abierto ambientada en el Lejano Oeste. Encarnas a Arthur Morgan, forajido de la banda de Van der Linde, en una historia madura con exploración, caza, tiroteos y un mundo vivo que reacciona a tus decisiones. Destaca por su narrativa, realismo y apartado técnico sobresaliente.","popularidad":4,"trailer":"https://www.youtube.com/watch?v=eaW0tYpxyp0","categoria":"Aventura"},
]

with Session() as db:
    for j in juegos:
        # evita duplicados por nombre
        exists = db.execute(select(Game).where(Game.nombre == j["nombre"])).scalar_one_or_none()
        if not exists:
            db.add(Game(**j))
    db.commit()
print("✅ Seed insertado")
